id: f7ea48031fdc4ec08964ef513dac6158
initial_creation_type: ocr
source_metadata:
  volumes:
    d1a59351c0f94f25a434e8c8ef087315:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ''
      total_pages: 1498
      volume_number: 65
